apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: common-datastore
resources:
  - ../../base
  - maestro-mariadb.init.sql.configmap.yaml
  - maestro-mariadb.configmap.yaml
  - maestro-mariadb.ddl.sql.configmap.yaml
  - maestro-mariadb.dml.sql.configmap.yaml
  - maestro-mariadb.viola.sql.configmap.yaml
  #- mariadb.trombone.sql.configmap.yaml

images:
  - name: mariadb
    newName: 10.0.10.6:8080/maestro/mariadb
    #newName: harbor.okestro-k8s.cld/maestro/maestro/mariadb # 테스트용
    newTag: 10.11-jammy

patchesStrategicMerge:
  - patch-pvc.yaml
  - patch-sql.configmap.yaml