apiVersion: v1
kind: ConfigMap
metadata:
  name: maestro-mariadb-viola-sql-config
  namespace: common-datastore
data:
  maestro-viola.sql: |
    USE OCP_CONSOLE;
    -- MySQL dump 10.13  Distrib 5.7.43, for osx10.18 (x86_64)
    --
    -- Host: maestro.okestro.cloud    Database: OCP_CONSOLE
    -- ------------------------------------------------------
    -- Server version	11.1.2-MariaDB-1:11.1.2+maria~ubu2204-log

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

    --
    -- Table structure for table `KUBERNETES_RULE`
    --

    DROP TABLE IF EXISTS `KUBERNETES_RULE`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `KUBERNETES_RULE` (
      `RULE_NO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '룰 번호',
      `RULE_NAME` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT '룰 이름',
      `DC` text CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT '룰 설명',
      `NMSPC_NAME` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT '네임스페이스 이름',
      `PROVIDER_ID` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT '생성자',
      `CRTC_POINT` bigint(20) DEFAULT NULL COMMENT '임계치',
      `TYPE` varchar(3) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT '유형',
      `INEQUALITY` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT '부등호',
      `CREATE_DATE` datetime DEFAULT NULL COMMENT '생성 일시',
      `UPDATE_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
      `DELETE_AT` varchar(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT '삭제 여부',
      `RSRC_QUOTA` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT '리소스쿼터 이름',
      PRIMARY KEY (`RULE_NO`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `OCP_AUDIT_LOG`
    --

    DROP TABLE IF EXISTS `OCP_AUDIT_LOG`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `OCP_AUDIT_LOG` (
      `ACTION` varchar(20) DEFAULT NULL,
      `IP_ADDRESS` varchar(50) DEFAULT NULL,
      `DC` text DEFAULT NULL COMMENT '설명',
      `CREATE_DATE` datetime DEFAULT NULL COMMENT '생성일',
      `LOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
      `PROVIDER_ID` varchar(40) DEFAULT NULL COMMENT '공급자 아이디 ',
      `STATUS` varchar(20) DEFAULT NULL COMMENT '상태',
      `RESOURCE_TYPE` varchar(20) DEFAULT NULL COMMENT '리소스 타입',
      PRIMARY KEY (`LOG_NO`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='비올라 감사로그';
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `OCP_CLUSTER`
    --

    DROP TABLE IF EXISTS `OCP_CLUSTER`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `OCP_CLUSTER` (
      `CLUSTER_NO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '클러스터 키',
      `PROVIDER_ID` varchar(45) NOT NULL COMMENT '공급자 아이디',
      `CLUSTER_NAME` varchar(50) NOT NULL COMMENT '클러스터 이름',
      `CLUSTER_TYPE` varchar(40) DEFAULT NULL COMMENT '클러스터 유형',
      `VERSION` varchar(20) DEFAULT NULL COMMENT '버젼',
      `API_URL` varchar(200) DEFAULT NULL COMMENT 'API URL',
      `PROMETHEUS_API_URL` varchar(200) DEFAULT NULL COMMENT 'Prometheus API URL',
      `OAUTH_API_URL` varchar(200) DEFAULT NULL COMMENT 'OAuth API URL',
      `ID` varchar(100) DEFAULT NULL COMMENT '아이디',
      `PASSWORD` mediumtext DEFAULT NULL COMMENT '비빌번호',
      `CREATE_DATE` datetime DEFAULT NULL COMMENT '생성 일시',
      `CLUSTER_TOKEN` mediumtext DEFAULT NULL,
      `PRODUCT_TYPE` varchar(40) DEFAULT NULL,
      `DELETE_AT` varchar(1) DEFAULT NULL,
      PRIMARY KEY (`CLUSTER_NO`)
    ) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `OCP_CLUSTER_NMSPC`
    --

    DROP TABLE IF EXISTS `OCP_CLUSTER_NMSPC`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `OCP_CLUSTER_NMSPC` (
      `NMSPC_NO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '네임스페이스 번호',
      `PROJECT_CLUSTER_NO` bigint(20) DEFAULT NULL COMMENT '프로젝트 클러스터 번호',
      `NMSPC_NAME` varchar(50) DEFAULT NULL COMMENT '네임스페이스 이름',
      `CREATE_DATE` datetime DEFAULT NULL COMMENT '생성 일시',
      `CREATE_USER` varchar(100) DEFAULT NULL COMMENT '생성자 아이디',
      `UPDATE_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
      `UPDATE_USER` varchar(100) DEFAULT NULL COMMENT '수정자 아이디',
      `DELETE_AT` varchar(1) DEFAULT NULL COMMENT '삭제 여부',
      PRIMARY KEY (`NMSPC_NO`)
    ) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `OCP_NMSPC_MEMBER`
    --

    DROP TABLE IF EXISTS `OCP_NMSPC_MEMBER`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `OCP_NMSPC_MEMBER` (
      `MEMBER_NO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '멤버 번호',
      `PROJECT_ID` varchar(45) DEFAULT NULL COMMENT '프로젝트 아이디',
      `CLUSTER_NO` bigint(20) DEFAULT NULL COMMENT '클러스터 번호',
      `NMSPC_NO` bigint(20) DEFAULT NULL COMMENT '네임스페이스 번호',
      `NMSPC_NAME` varchar(50) DEFAULT NULL COMMENT '네임스페이스 이름',
      `USER_ID` varchar(100) DEFAULT NULL COMMENT '사용자 아이디',
      `ROLE` varchar(50) DEFAULT NULL COMMENT '역할',
      `CREATE_DATE` datetime DEFAULT NULL COMMENT '생성 일시',
      `CREATE_USER` varchar(100) DEFAULT NULL COMMENT '생성자 아이디',
      `UPDATE_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
      `UPDATE_USER` varchar(100) DEFAULT NULL COMMENT '수정자 아이디',
      PRIMARY KEY (`MEMBER_NO`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `OCP_PROJECT`
    --

    DROP TABLE IF EXISTS `OCP_PROJECT`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `OCP_PROJECT` (
      `PROJECT_ID` varchar(45) NOT NULL COMMENT '프로젝트 아이디',
      `PROJECT_NAME` varchar(45) DEFAULT NULL COMMENT '프로젝트 이름',
      `PROJECT_INFO` text DEFAULT NULL COMMENT '프로젝트 정보',
      `PROJECT_BEGIN_DATE` varchar(8) DEFAULT NULL COMMENT '프로젝트 시작일',
      `PROJECT_END_DATE` varchar(8) DEFAULT NULL COMMENT '프로젝트 종료일',
      `STATUS_CODE` varchar(10) DEFAULT NULL COMMENT '상태 코드',
      `CREATE_DATE` datetime DEFAULT NULL COMMENT '생성 일시',
      `CREATE_USER` varchar(100) DEFAULT NULL COMMENT '생성자 아이디',
      `UPDATE_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
      `UPDATE_USER` varchar(100) DEFAULT NULL COMMENT '수정자 아이디',
      `DELETE_AT` varchar(1) DEFAULT NULL COMMENT '삭제 여부',
      PRIMARY KEY (`PROJECT_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `OCP_PROJECT_CLUSTER`
    --

    DROP TABLE IF EXISTS `OCP_PROJECT_CLUSTER`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `OCP_PROJECT_CLUSTER` (
      `PROJECT_CLUSTER_NO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '클러스터 번호',
      `PROJECT_ID` varchar(45) DEFAULT NULL COMMENT '프로젝트 아이디',
      `PROVIDER_ID` varchar(45) DEFAULT NULL COMMENT '공급자 아이디',
      `CLUSTER_NO` bigint(20) DEFAULT NULL COMMENT '클러스터 이름',
      `CLUSTER_TYPE` varchar(40) DEFAULT NULL COMMENT '클러스터 유형',
      `CREATE_DATE` datetime DEFAULT NULL COMMENT '생성 일시',
      `API_URL` varchar(200) DEFAULT NULL COMMENT 'API URL',
      `NODE` int(11) DEFAULT NULL COMMENT '노드',
      `DC` text DEFAULT NULL COMMENT '설명',
      `CREATE_USER` varchar(100) DEFAULT NULL COMMENT '생성자 아이디',
      `UPDATE_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
      `UPDATE_USER` varchar(100) DEFAULT NULL COMMENT '수정자 아이디',
      `DELETE_AT` varchar(1) DEFAULT NULL COMMENT '삭제 여부',
      PRIMARY KEY (`PROJECT_CLUSTER_NO`)
    ) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `OCP_PROJECT_MEMBER`
    --

    DROP TABLE IF EXISTS `OCP_PROJECT_MEMBER`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `OCP_PROJECT_MEMBER` (
      `PROJECT_MEMBER_NO` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '프로젝트 멤버 번호',
      `PROJECT_ID` varchar(45) DEFAULT NULL COMMENT '프로젝트 아이디',
      `USER_ID` varchar(100) DEFAULT NULL COMMENT '사용자 아이디',
      `PROJECT_NAME` varchar(45) DEFAULT NULL COMMENT '프로젝트 이름',
      `PROJECT_ROLE` varchar(10) DEFAULT NULL COMMENT '프로젝트 권한',
      `CREATE_DATE` datetime DEFAULT NULL COMMENT '생성 일시',
      `CREATE_USER` varchar(100) DEFAULT NULL COMMENT '생성자 아이디',
      `UPDATE_DATE` datetime DEFAULT NULL COMMENT '수정 일시',
      `UPDATE_USER` varchar(100) DEFAULT NULL COMMENT '수정자 아이디',
      PRIMARY KEY (`PROJECT_MEMBER_NO`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `OCP_USER`
    --

    DROP TABLE IF EXISTS `OCP_USER`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `OCP_USER` (
      `USER_ID` varchar(100) NOT NULL COMMENT '사용자 아이디',
      `USER_NAME` varchar(100) DEFAULT NULL COMMENT '사용자 이름',
      `EMAIL` varchar(100) DEFAULT NULL COMMENT '이메일',
      `EMP_NO` varchar(10) DEFAULT NULL COMMENT '사원 번호',
      `DEPT_NO` varchar(10) DEFAULT NULL COMMENT '부서 번호',
      `DEPT_NAME` varchar(100) DEFAULT NULL COMMENT '부서 이름',
      PRIMARY KEY (`USER_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;
    /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

    -- Dump completed on 2023-10-04 15:48:01
