apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maestro-mariadb
  labels:
    app: maestro
    tier: db
spec:
  template:
    spec:
      containers:
        - name: mariadb
          image: mariadb
          volumeMounts:
            - name: maestro-mariadb-ddl-sql-config
              mountPath: /docker-entrypoint-initdb.d/maestro-ddl.sql
              subPath: maestro-ddl.sql
            - name: maestro-mariadb-dml-sql-config
              mountPath: /docker-entrypoint-initdb.d/maestro-dml.sql
              subPath: maestro-dml.sql
            - name: maestro-mariadb-viola-sql-config
              mountPath: /docker-entrypoint-initdb.d/maestro-viola.sql
              subPath: maestro-viola.sql
            #- name: mariadb-trombone-sql-config
            #  mountPath: /docker-entrypoint-initdb.d/trombone.sql
            #  subPath: trombone.sql
      volumes:
        - name: maestro-mariadb-ddl-sql-config
          configMap:
            name: maestro-mariadb-ddl-sql-config
            items:
              - key: maestro-ddl.sql
                path: maestro-ddl.sql
        - name: maestro-mariadb-dml-sql-config
          configMap:
            name: maestro-mariadb-dml-sql-config
            items:
              - key: maestro-dml.sql
                path: maestro-dml.sql
        - name: maestro-mariadb-viola-sql-config
          configMap:
            name: maestro-mariadb-viola-sql-config
            items:
              - key: maestro-viola.sql
                path: maestro-viola.sql
        # 트럼본 SQL은 전달받은 SQL 파일에 문법 오류가 있어서 새 파일 받은 후 적용해야함.
        #- name: mariadb-trombone-sql-config
        #  configMap:
        #    name: mariadb-trombone-sql-config
        #    items:
        #      - key: trombone.sql
        #        path: trombone.sql