apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: common-datastore

images:
- name: busybox
  newName: 10.10.20.100:55000/maestro/dip/busybox
  newTag: "1.28"
- name: unsealer
  newName: 10.10.20.100:55000/maestro/dip/unsealer
  newTag: v0.0.1
