apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: delta-engine-stress-test
  name: delta-engine-stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delta-engine-stress-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: delta-engine-stress-test
    spec:
      containers:
      - image: jaeseung2/stress:local.5
        imagePullPolicy: Always
        name: delta-engine-stress-test
        ports:
        - containerPort: 8080
        resources: {}
        
        env:
        - name: TUBA_SETTING_FILENAME
          value: "setting.yml"
        - name: TUBA_TEST_MAX_COUNT
          value: "10"
        - name: TUBA_KAFKA_SERVER
          value: "kafka-cluster-kafka-brokers:9092"
        - name: TUBA_KAFKA_PRODUCER_TOPIC
          value: "tuba-metric-topic"
      

---
apiVersion: v1
kind: Service
metadata:
  name: delta-engine-stress-test
spec:
  selector:
    app: delta-engine-stress-test
  ports:
    - port: 8080
      targetPort: 8080
