kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: common-datastore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  storageClassName: nfs-client
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv-redis-nfs
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: nfs-client
#  persistentVolumeReclaimPolicy: Retain

# gcp pv
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv-redis-standard-rwo
#spec:
#  gcePersistentDisk:
#    pdName: pv-redis-pd
#    fsType: ext4
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: standard-rwo
#  persistentVolumeReclaimPolicy: Retain

