apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: common-datastore
data:
  redis.conf: |
    # Redis configuration file example.
    #
    # Note that in order to read the configuration file, Redis must be
    # started with the file path as first argument:
    #
    # ./redis-server /path/to/redis.conf
    bind 0.0.0.0
    protected-mode yes
    
    # configurations for snaposhot and AOF
    # read more : https://redis.io/docs/manual/persistence/
    dbfilename dump.rdb
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
    
    # Enabled ACL based auth. 
    protected-mode yes

    # This will be set by our Init Container
    # replicaof redis-master-0.redis-master.redis.svc.cluster.local 6379

    masterauth admin
    requirepass admin
    
    aclfile /conf/acl/users.acl
    port 6379
