apiVersion: v1
kind: PersistentVolume
metadata:
  name: maridb-pv
spec:
  storageClassName: mariadb-storage
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.212
    path: /share/mariadb
