apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maestro-mariadb
  labels:
    app: maestro
    tier: db
spec:
  template:
    spec:
      containers:
        - name: mariadb
          image: mariadb
          volumeMounts:
            - name: maestro-mariadb-ddl-sql-config
              mountPath: /docker-entrypoint-initdb.d/maestro-ddl.sql
              subPath: maestro-ddl.sql
            - name: maestro-mariadb-dml-sql-config
              mountPath: /docker-entrypoint-initdb.d/maestro-dml.sql
              subPath: maestro-dml.sql
            - name: maestro-mariadb-viola-sql-config
              mountPath: /docker-entrypoint-initdb.d/maestro-viola.sql
              subPath: maestro-viola.sql
            # 23/10/26 창훈님 요청으로 추가 
            - name: maestro-mariadb-ip-pool-sql-config
              mountPath: /docker-entrypoint-initdb.d/maestro-ip-pool.sql
              subPath: maestro-ip-pool.sql
      volumes:
        - name: maestro-mariadb-ddl-sql-config
          configMap:
            name: maestro-mariadb-ddl-sql-config
            items:
              - key: maestro-ddl.sql
                path: maestro-ddl.sql
        - name: maestro-mariadb-dml-sql-config
          configMap:
            name: maestro-mariadb-dml-sql-config
            items:
              - key: maestro-dml.sql
                path: maestro-dml.sql
        - name: maestro-mariadb-viola-sql-config
          configMap:
            name: maestro-mariadb-viola-sql-config
            items:
              - key: maestro-viola.sql
                path: maestro-viola.sql
        # 23/10/26 창훈님 요청으로 추가        
        - name: maestro-mariadb-ip-pool-sql-config
          configMap:
            name: maestro-mariadb-ip-pool-sql-config
            items:
              - key: maestro-ip-pool.sql
                path: maestro-ip-pool.sql