apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: common-datastore
resources:
  - ../../base
  - maestro-mariadb.configmap.yaml

images:
  - name: mariadb
    newName: 10.10.10.110:55000/maestro/dip/mariadb
    newTag: 10.11-jammy

patchesStrategicMerge:
  - patch-pvc.yaml
