apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: common-datastore

images:
- name: busybox
  newName: 10.0.10.6:8080/maestro/busybox
  newTag: "1.28"
- name: unsealer
  newName: 10.0.10.6:8080/maestro/unsealer
  newTag: v0.0.1
