apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: common-datastore
images:
  - name: vault
    newName: harbor.cmp.cloud.go.kr/maestro/nirs/vault
    newTag: "1.14.1"
  - name: chown
    newName: harbor.cmp.cloud.go.kr/maestro/nirs/kubectl
    newTag: v1 
  - name: busybox
    newName: harbor.cmp.cloud.go.kr/maestro/nirs/busybox
    newTag: "1.28"
patchesStrategicMerge:
  - patch-pvc.yaml