---
# Source: logstash/templates/configmap-pipeline.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-logstash-pipeline
  labels:
    app: "logstash-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "logstash"
data:
  topic-contrabass.conf: |
        input {
          kafka {
            bootstrap_servers => "kafka-cluster-kafka-bootstrap.hwson.svc:9092"
            topics => ["delta-topic"]
            codec => "json"
          }
        }
        
        filter {
          if "metricbeat" in [agent][type] {
            if "socket_summary" in [metricset][name] {
              drop { }
            }
            if "process" in [metricset][name] {
              drop { }
            }
            if "node03.dev.klid.go.kr" in [host][hostname] {
              drop { }
            }
        
        #windows fiexd type으로 사용 하고 있음.
            if "filesystem" in [metricset][name] {
              if "ocfs" not in [system][filesystem][type] and "ext" not in [system][filesystem][type] and "fixed" not in [system][filesystem][type]{
                drop { }
              }
            }
        #kubernetes drop
            if "metricbeat" in [agent][type] {
              if "kubernetes" in [service][type] {
                if "proxy" in [metricset][name] or "volume" in [metricset][name] or "node" in [metricset][name] or "apiserver" in [metricset][name] or "system" in [metricset][name] or "state_daemonset" in [metricset][name] or "state_deployment" in [metricset][name] or "state_container" in [metricset][name] or "state_pod" in [metricset][name] or "state_service" in [metricset][name] or "state_replicaset" in [metricset][name] {
                  drop { }
                }
              }
            }
        
        
            mutate {
              add_field => {
                "tmp_timestamp" => ""
              }
            }
        
            ruby {
              code => "event.set('tmp_timestamp', event.get('@timestamp').time.strftime('%Y-%m-%d %H:%M:%S'))"
            }
        
            grok {
              match => {
                "tmp_timestamp" => "%{INT:year_tmp}-%{MONTHNUM:month_tmp}-%{MONTHDAY:day_tmp} %{INT:hour_tmp}:%{INT:minute_tmp}:%{INT:second_tmp}"
              }
            }
        
            mutate {
              convert => { "second_tmp" => "integer" }
            }
        
            mutate {
              add_field => {
                "datetime" => "%{year_tmp}-%{month_tmp}-%{day_tmp} %{hour_tmp}:%{minute_tmp}:%{second_tmp}"
              }
              convert => { "datetime" => "string" }
        
              rename => {
                "[system][process][cgroup][cpuacct][percpu][1]" => "[system][process][cgroup][cpuacct][percpu][c01]"
                "[system][process][cgroup][cpuacct][percpu][2]" => "[system][process][cgroup][cpuacct][percpu][c02]"
                "[system][process][cgroup][cpuacct][percpu][3]" => "[system][process][cgroup][cpuacct][percpu][c03]"
                "[system][process][cgroup][cpuacct][percpu][4]" => "[system][process][cgroup][cpuacct][percpu][c04]"
                "[system][process][cgroup][cpuacct][percpu][5]" => "[system][process][cgroup][cpuacct][percpu][c05]"
                "[system][process][cgroup][cpuacct][percpu][6]" => "[system][process][cgroup][cpuacct][percpu][c06]"
                "[system][process][cgroup][cpuacct][percpu][7]" => "[system][process][cgroup][cpuacct][percpu][c07]"
                "[system][process][cgroup][cpuacct][percpu][8]" => "[system][process][cgroup][cpuacct][percpu][c08]"
                "[system][process][cgroup][cpuacct][percpu][9]" => "[system][process][cgroup][cpuacct][percpu][c09]"
                "[system][process][cgroup][cpuacct][percpu][10]" => "[system][process][cgroup][cpuacct][percpu][c10]"
                "[system][process][cgroup][cpuacct][percpu][11]" => "[system][process][cgroup][cpuacct][percpu][c11]"
                "[system][process][cgroup][cpuacct][percpu][12]" => "[system][process][cgroup][cpuacct][percpu][c12]"
                "[system][process][cgroup][cpuacct][percpu][13]" => "[system][process][cgroup][cpuacct][percpu][c13]"
                "[system][process][cgroup][cpuacct][percpu][14]" => "[system][process][cgroup][cpuacct][percpu][c14]"
                "[system][process][cgroup][cpuacct][percpu][15]" => "[system][process][cgroup][cpuacct][percpu][c15]"
                "[system][process][cgroup][cpuacct][percpu][16]" => "[system][process][cgroup][cpuacct][percpu][c16]"
                "[system][process][cgroup][cpuacct][percpu][17]" => "[system][process][cgroup][cpuacct][percpu][c17]"
                "[system][process][cgroup][cpuacct][percpu][18]" => "[system][process][cgroup][cpuacct][percpu][c18]"
                "[system][process][cgroup][cpuacct][percpu][19]" => "[system][process][cgroup][cpuacct][percpu][c19]"
                "[system][process][cgroup][cpuacct][percpu][20]" => "[system][process][cgroup][cpuacct][percpu][c20]"
                "[system][process][cgroup][cpuacct][percpu][21]" => "[system][process][cgroup][cpuacct][percpu][c21]"
                "[system][process][cgroup][cpuacct][percpu][22]" => "[system][process][cgroup][cpuacct][percpu][c22]"
                "[system][process][cgroup][cpuacct][percpu][23]" => "[system][process][cgroup][cpuacct][percpu][c23]"
                "[system][process][cgroup][cpuacct][percpu][24]" => "[system][process][cgroup][cpuacct][percpu][c24]"
                "[system][process][cgroup][cpuacct][percpu][25]" => "[system][process][cgroup][cpuacct][percpu][c25]"
                "[system][process][cgroup][cpuacct][percpu][26]" => "[system][process][cgroup][cpuacct][percpu][c26]"
                "[system][process][cgroup][cpuacct][percpu][27]" => "[system][process][cgroup][cpuacct][percpu][c27]"
                "[system][process][cgroup][cpuacct][percpu][28]" => "[system][process][cgroup][cpuacct][percpu][c28]"
                "[system][process][cgroup][cpuacct][percpu][29]" => "[system][process][cgroup][cpuacct][percpu][c29]"
                "[system][process][cgroup][cpuacct][percpu][30]" => "[system][process][cgroup][cpuacct][percpu][c30]"
                "[system][process][cgroup][cpuacct][percpu][31]" => "[system][process][cgroup][cpuacct][percpu][c31]"
                "[system][process][cgroup][cpuacct][percpu][32]" => "[system][process][cgroup][cpuacct][percpu][c32]"
        
                #"[system][load][1]" => "[system][load][1m]"
                #"[system][load][5]" => "[system][load][5m]"
                #"[system][load][15]" => "[system][load][15m]"
                #"[system][load][norm][1]" => "[system][load][norm][1m]"
                #"[system][load][norm][5]" => "[system][load][norm][5m]"
                #"[system][load][norm][15]" => "[system][load][norm][15m]"
              }
        
              remove_field => [ "year_tmp","month_tmp","day_tmp","hour_tmp","minute_tmp","second_tmp","sec","tmp_timestamp" ]
            }
        
            date {
              match => ["datetime", "yyyy-MM-dd HH:mm:ss"]
              timezone => "UTC"
              locale => "ko"
              target => "datetime"
            }
        
          }
          else if "filebeat" in [agent][type] {
            if "syslog" in [log][file][path] {
              grok {
                match => {
                  #message" => "%{HOSTNAME:hostname} %{SYSLOGPROG}: %{GREEDYDATA:tmp_message}"
                  "message" => "%{GREEDYDATA:tmp_message}"
                }
              }
        
              mutate {
                replace => {
                  "message" => "%{tmp_message}"
                  #"message" => "%{HOSTNAME:hostname} %{SYSLOGPROG}: %{GREEDYDATA:tmp_message}"
                  #"message" => "%{message}"
                }
        
                remove_field => [ "hostname", "tmp_message" ]
              }
            }
          }
        }
        
        output {
         
          if "filebeat" in [agent][type] {
            if "syslog" in [log][file][path] {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-file-log-syslog"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            }
            else if "auth" in [log][file][path] {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-file-log-auth"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            }
            else if "nova-compute" in [log][file][path] {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-file-nova-compute"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            }
            else if "nova-api" in [log][file][path] {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-file-nova-api"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            }
            else if "nova-scheduler" in [log][file][path] {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-file-nova-scheduler"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            }
            else if "containers" in [log][file][path] {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-file-log-container"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            } else {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-file-${[metricset][name]}"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            }
          } else if "metricbeat" in [agent][type] {
            if "kubernetes" in [service][type] {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-metric-kube-%{[metricset][name]}"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            } else if "vsphere" in [service][type] {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-metric-vsphere"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            } else {
              opensearch {
                hosts => ["https://opensearch-cluster-master:9200"]
                index => "oke-metric-%{[metricset][name]}"
                user => "admin"
                password => "admin"
                ssl => false
                ssl_certificate_verification => false
              }
            }
          } else if "metric_collector" in [agent][type] {
            if "vmware" in [service][type] {
              if "vsphere" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-vmware-vsphere"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "vcenter" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-vmware-vcenter"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "cluster" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-vmware-cluster"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "host" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-vmware-host"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "datastore" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-vmware-datastore"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "virtualmachine" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-vmware-vm"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              }
            } else if "openstack" in [service][type] {
              if "vm" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-openstack-vm"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "loadbalancer" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-openstack-loadbalancer"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "baremetal" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-openstack-baremetal"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "network" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-openstack-network"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "image" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-openstack-image"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              }
            } else if "netapp" in [service][type] {
              if "filestorage" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-netapp-filestorage"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              }
            } else if "k8s" in [service][type] {
              if "node" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-k8s-node"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "namespace" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-k8s-namespace"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "pod" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-k8s-pod"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "storage" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-k8s-storage"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "cluster" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-k8s-cluster"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              } else if "workload" in [service][adapter] {
                opensearch {
                  hosts => ["https://opensearch-cluster-master:9200"]
                  index => "oke-metric-k8s-workload"
                  user => "admin"
                  password => "admin"
                  ssl => false
                  ssl_certificate_verification => false
                }
              }
            }
          } else if "filestorage" in [agent][type] {
            opensearch {
              hosts => ["https://opensearch-cluster-master:9200"]
              index => "oke-file-storage"
              user => "admin"
              password => "admin"
              ssl => false
              ssl_certificate_verification => false
            }
          } else {
            opensearch {
              hosts => ["https://opensearch-cluster-master:9200"]
              index => "oke-kube-state-pod"
              user => "admin"
              password => "admin"
              ssl => false
              ssl_certificate_verification => false
            }
          }
        }

