---
# Source: logstash/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: "logstash-logstash"
  labels:
    app: "logstash-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "logstash"
  annotations:
    {}
spec:
  type: NodePort
  selector:
    app: "logstash-logstash"
    chart: "logstash"
    release: "logstash"
  ports:
    - name: beats
      nodePort: 31100
      port: 5044
      protocol: TCP
    - name: http
      nodePort: 31200
      port: 8080
      protocol: TCP
