apiVersion: v1
kind: ConfigMap
metadata:
  name: maestro-mariadb-init-sql-config
  namespace: common-datastore
data:
  init.sql: |
    USE mysql;
    CREATE user 'maestro'@'%' identified by 'okestro2018';
    CREATE DATABASE IF NOT EXISTS maestro;
    CREATE DATABASE IF NOT EXISTS cloud_service;
    grant ALL PRIVILEGES on *.* to 'maestro'@'%';
    flush privileges;