apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maestro-mariadb
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: nfs-client2
        volumeMode: Filesystem
