apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: common-datastore
resources:
  #- ../../../../../../../Desktop/1.4-datastore/mariadb/base
  - maestro-mariadb.init.sql.configmap.yaml
  - maestro-mariadb.configmap.yaml
  - maestro-mariadb.ddl.sql.configmap.yaml
  - maestro-mariadb.dml.sql.configmap.yaml
  - maestro-mariadb.viola.sql.configmap.yaml
  - maestro-mariadb.ip.pool.sql.configmap.yaml
  - ../../base
#  - maestro-mariadb.configmap.yaml
images:
  - name: mariadb
    newName: harbor.cmp.cloud.go.kr/maestro/nirs/mariadb
    newTag: 10.11-jammy

patchesStrategicMerge:
  - patch-pvc.yaml
  - patch-sql.configmap.yaml