apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
# - kafka.yaml

namespace: common-datastore
images:
  - name: strimzi-cluster-operator
    newName: harbor.okestro-k8s.cld/maestro/maestro/operator #변경
    newTag: "0.36.1-amd64" #변경

configMapGenerator:
- name: kafka-images-config
  literals:
  - REGISTRY=harbor.okestro-k8s.cld/maestro/maestro #변경

