apiVersion: v1
kind: Pod
metadata:
  name: echo-lp
  labels:
    app: echo
spec:
  containers:
    - name: app
      image: ghcr.io/subicura/echo:v1
      # livenessProbe
      livenessProbe:
        httpGet:
          path: /
          port: 8080
      # readinessProbe
      readinessProbe:
        httpGet:
          path: /
          port: 8080
