apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0000
  namespace: default
  labels:
    storage: nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /tmp/mssql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dx-dev2-10
          - dx-dev2-6
          - dx-dev2-7
          - dx-dev2-8
          - dx-dev2-9
