apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: common-datastore
images:
- name: busybox
  newName: 10.10.20.100:55000/maestro/dip/busybox
  newTag: "1.28"
- name: chown
  newName: 10.10.20.100:55000/maestro/dip/kubectl
  newTag: v1
- name: vault
  newName: 10.10.20.100:55000/maestro/dip/vault
  newTag: "1.14.1"
patchesStrategicMerge:
- patch-pvc.yaml
