apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: common-datastore
resources:
  - redis-statefulset.yaml
  - redis-service.yaml
#  - redis-sentinel.yaml redis 상태 확인 후 따로 배포 필요 (업데이트 필요 )