apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  ports:
    - name: np1
      port: 9000
      targetPort: 9000
      nodePort: 30333
    - name: np2
      port: 38185
      targetPort: 38185
      nodePort: 30334
  selector:
    app: minio
