apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-rest.fullname" . }}
  labels:
    {{- include "kafka-rest.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: tcp
  selector:
    {{- include "kafka-rest.selectorLabels" . | nindent 4 }}
