apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: common-datastore

images:
  - name: unsealer
    newName: harbor.cmp.cloud.go.kr/maestro/nirs/unsealer
    newTag: v0.0.1

