apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: common-datastore
# patches:
#   - target:
#       kind: Deployment
#     path: patches/taint-patch.yaml

images:
  - name: unsealer
    newName: 10.10.10.110:55000/maestro/dip/unsealer
    newTag: v0.0.1
  - name: init
    newName: 10.10.10.110:55000/maestro/dip/busybox
    newTag: "1.28"
