apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: common-datastore
images:
- name: busybox
  newName: 10.0.10.6:8080/maestro/busybox
  newTag: "1.28"
- name: chown
  newName: 10.0.10.6:8080/maestro/kubectl
  newTag: v1
- name: vault
  newName: 10.0.10.6:8080/maestro/vault
  newTag: "1.14.1"
patchesStrategicMerge:
- patch-pvc.yaml
