apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: common-datastore
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: nfs-client
        volumeMode: Filesystem