apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
# - kafka.yaml

namespace: common-datastore
images:
- name: strimzi-cluster-operator
  newName: 10.10.20.100:55000/maestro/dip/operator
  newTag: 0.36.1-amd64

configMapGenerator:
- literals:
  - REGISTRY=10.10.20.100:55000/maestro/dip
  name: kafka-images-config
