apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
 name: kafka-cluster
spec:
 kafka:
   version: 3.3.2
   replicas: 3
   listeners:
     - name: plain
       port: 9092
       type: internal
       tls: false
     - name: tls
       port: 9093
       type: internal
       tls: true
     - name: external
       port: 9094
       type: nodeport
       tls: false
       configuration:
         bootstrap:
           nodePort: 32100
         brokers:
         - broker: 0
           nodePort: 32000
         - broker: 1
           nodePort: 32001
         - broker: 2
           nodePort: 32002
   config:
     offsets.topic.replication.factor: 3
     transaction.state.log.replication.factor: 3
     transaction.state.log.min.isr: 3
     default.replication.factor: 3
     min.insync.replicas: 2
     inter.broker.protocol.version: "3.3"
   storage:
     type: jbod
     volumes:
     - id: 0
       type: persistent-claim
       class: local-storage
       size: 10Gi
       deleteClaim: false
 zookeeper:
   replicas: 3
   storage:
     type: persistent-claim
     class: local-zookeeper-storage
     size: 100Gi
     deleteClaim: false
 entityOperator:
   topicOperator: {}
   userOperator: {}

