apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 34.69.129.26
    path: /root/nfs_volumn/kafka
   
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 34.69.129.26
    path: /root/nfs_volumn/kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume-3
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 34.69.129.26
    path: /root/nfs_volumn/kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-zookeeper-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 34.69.129.26
    path: /root/nfs_volumn/kafka/zk1
   
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: local-zookeeper-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 34.69.129.26
    path: /root/nfs_volumn/kafka/zk2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-volume-3
  labels:
    type: local
spec:
  storageClassName: local-zookeeper-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 34.69.129.26
    path: /root/nfs_volumn/kafka/zk3
