apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: common-datastore
images:
  - name: vault
    newName: harbor.okestro-k8s.cld/maestro/vault
    newTag: "1.14"
  - name: init
    newName: harbor.okestro-k8s.cld/maestro/kubectl
    newTag: v1 
  - name: busybox
    newName: harbor.okestro-k8s.cld/maestro/busybox
    newTag: "1.28"
patchesStrategicMerge:
  - patch-pvc.yaml