apiVersion: v1
kind: Service
metadata:
  name: transit-secret-engine
  namespace: common-datastore
  labels:
    app.kubernetes.io/name: transit-secret-engine
    app.kubernetes.io/instance: vault
spec:
  ports:
    - port: 8100
      targetPort: 8100
  selector:
    app.kubernetes.io/name: transit-secret-engine
    app.kubernetes.io/instance: vault
    component: server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transit-secret-engine
  namespace: common-datastore
  labels:
    app.kubernetes.io/name: transit-secret-engine
    app.kubernetes.io/instance: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: transit-secret-engine-server-binding
  labels:
    app.kubernetes.io/name: transit-secret-engine
    app.kubernetes.io/instance: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: transit-secret-engine
    namespace: common-datastore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: common-datastore
  name: transit-secret-engine-discovery-role
  labels:
    app.kubernetes.io/name: transit-secret-engine
    app.kubernetes.io/instance: vault
rules:
  - apiGroups: [""]
    resources: ["pods","pods/exec"]
    verbs: ["get", "watch", "list", "update", "patch", "create"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: transit-secret-engine-discovery-rolebinding
  namespace: common-datastore
  labels:
    app.kubernetes.io/name: transit-secret-engine
    app.kubernetes.io/instance: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: transit-secret-engine-discovery-role
subjects:
  - kind: ServiceAccount
    name: transit-secret-engine
    namespace: common-datastore
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transit-secret-engine
  namespace: common-datastore
  labels:
    app.kubernetes.io/name: transit-secret-engine
    app.kubernetes.io/instance: vault
spec:
  serviceName: transit-secret-engine
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app.kubernetes.io/name: transit-secret-engine
      app.kubernetes.io/instance: vault
      component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transit-secret-engine
        app.kubernetes.io/instance: vault
        component: server
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: transit-secret-engine
                  app.kubernetes.io/instance: "vault"
                  component: server
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      serviceAccountName: transit-secret-engine
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 100
        fsGroup: 1000
      volumes:
        - name: config
          configMap:
            name: transit-secret-engine-config
        - name: home
          emptyDir: {}
      containers:
        - name: vault
          image: vault
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-ec"
          args:
            - |
              cp /vault/config/extraconfig-from-values.hcl /tmp/storageconfig.hcl;
              [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /tmp/storageconfig.hcl;
              [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /tmp/storageconfig.hcl;
              [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /tmp/storageconfig.hcl;
              [ -n "${API_ADDR}" ] && sed -Ei "s|API_ADDR|${API_ADDR?}|g" /tmp/storageconfig.hcl;
              [ -n "${TRANSIT_ADDR}" ] && sed -Ei "s|TRANSIT_ADDR|${TRANSIT_ADDR?}|g" /tmp/storageconfig.hcl;
              [ -n "${RAFT_ADDR}" ] && sed -Ei "s|RAFT_ADDR|${RAFT_ADDR?}|g" /tmp/storageconfig.hcl;
              /usr/local/bin/docker-entrypoint.sh vault server -config=/tmp/storageconfig.hcl
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VAULT_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8100"
            - name: VAULT_API_ADDR
              value: "http://$(POD_IP):8100"
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOME
              value: "/home/vault"
          volumeMounts:
            - name: secret-engine-data
              mountPath: /vault/data
              subPath: data
            - name: config
              mountPath: /vault/config
            - name: home
              mountPath: /home/vault
          ports:
            - containerPort: 8100
          readinessProbe:
            # Check status; unsealed vault servers return 0
            # The exit code reflects the seal status:
            #   0 - unsealed
            #   1 - error
            #   2 - sealed
            exec:
              command: ["/bin/sh", "-ec", "vault status -tls-skip-verify"]
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          lifecycle:
            # Vault container doesn't receive SIGTERM from Kubernetes
            # and after the grace period ends, Kube sends SIGKILL.  This
            # causes issues with graceful shutdowns such as deregistering itself
            # from Consul (zombie services).
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  # Adding a sleep here to give the pod eviction a
                  # chance to propagate, so requests will not be made
                  # to this pod while it's terminating
                  "sleep 5 && kill -SIGTERM $(pidof vault)",
                ]
        - name: extract
          image: extract
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: secret-engine-data
              mountPath: /vault/data
              subPath: data
            - name: config
              mountPath: /vault/config
          command:
            - "sh"
            - "/vault/config/extract.sh"
  # volumeClaimTemplates:
  #   - metadata:
  #       name: secret-engine-data
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1Gi
  #       storageClassName: rook-ceph-block
  #       volumeMode: Filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transit-secret-engine-config
  namespace: common-datastore
  labels:
    app.kubernetes.io/name: transit-secret-engine
    app.kubernetes.io/instance: vault
data:
  extract.sh: |-
    #!/usr/bin/env bash
    set -uo pipefail

    chmod -R 777 /vault/data
    
    NAMESPACE=$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)
    INITIALIZED=$(kubectl exec pod/transit-secret-engine-0 -c vault -n $NAMESPACE -- vault status | grep -i "Initialized." | awk '{print $2}');
    
    echo $INITIALIZED;

    if [ "$INITIALIZED" = "true" ];then
            echo "initialized"
    else
            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault operator init -key-shares=1 -key-threshold=1 -format=json > /vault/data/transit.json
    fi

    VAULT_UNSEAL_KEY=$(cat /vault/data/transit.json | jq -r ".unseal_keys_b64[]");
    ROOT_TOKEN=$(cat /vault/data/transit.json | jq -r ".root_token");

    echo $VAULT_UNSEAL_KEY;
    echo $ROOT_TOKEN;
    
    SEALED=$(kubectl exec pod/transit-secret-engine-0 -c vault -n $NAMESPACE -- vault status | grep -i "Sealed." | awk '{print $2}');
    
    if [ "$SEALED" = "true" ];then
            echo "unsealing..."
            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault operator unseal $VAULT_UNSEAL_KEY;
            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault login $ROOT_TOKEN;
            #TRANSIT=$(kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault secrets list)
            #if [ -z "$TRANSIT" ]; then
            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault secrets enable transit;
            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault write -f transit/keys/autounseal;
            #fi

            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault policy write autounseal /vault/config/unseal-policy.hcl;
            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault auth enable kubernetes;
            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault write auth/kubernetes/config kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443";
            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault token create -orphan -policy="autounseal" -wrap-ttl=120 -period=24h | grep -i "wrapping_token:." | awk '{print $2}' > /vault/data/wrapping.txt;
            kubectl exec transit-secret-engine-0 -c vault -n $NAMESPACE -- vault unwrap $(cat /vault/data/wrapping.txt) | grep -i -m1 "token." | awk '{print $2}' > /vault/data/transit_token.txt;
    else
            echo "unsealed"
    fi

    #kubectl delete configmap vault-token -n $NAMESPACE
    #kubectl delete secret unsealer-secret -n $NAMESPACE
    kubectl create configmap vault-token --from-literal=TRANSIT_ADDR=http://transit-secret-engine.$NAMESPACE.svc.cluster.local:$TRANSIT_SECRET_ENGINE_SERVICE_PORT --from-literal=TRANSIT_TOKEN=$(cat /vault/data/transit_token.txt) -n $NAMESPACE
    kubectl create secret generic unsealer-secret --from-literal=token=$VAULT_UNSEAL_KEY -n $NAMESPACE

    sleep 99999999999

  unseal-policy.hcl: |-
    path "transit/encrypt/autounseal" {
      capabilities = ["update"]
    }

    path "transit/decrypt/autounseal" {
      capabilities = ["update"]
    }
  extraconfig-from-values.hcl: |-
    # disable memory locking. Memory locking is a security measure that prevents sensitive data from being swapped to disk, but it can cause issues on certain systems. 
    disable_mlock = true
    ui = false
    
    # a listener configuration for TCP connections.
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8100"
    }

    storage "file" {
      path = "/vault/data"
    }
    
    # Example configuration for using auto-unseal, using Google Cloud KMS. The
    # GKMS keys must already exist, and the cluster must have a service account
    # that is authorized to access GCP KMS.
    #seal "gcpckms" {
    #   project     = "vault-helm-dev"
    #   region      = "global"
    #   key_ring    = "vault-helm-unseal-kr"
    #   crypto_key  = "vault-helm-unseal-key"
    #}
