apiVersion: v1
kind: Service
metadata:
  name: maestro-mariadb
  namespace: common-datastore
  labels:
    app: maestro
    tier: db
spec:
  ports:
    - port: 3307
      name: tcp-maestro-db
      appProtocol: tcp
  selector:
    app: maestro
    tier: db
  clusterIP: None
