apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: post-vault
  namespace: common-datastore
spec:
 volumeClaimTemplates:
   - metadata:
       name: data
     spec:
       accessModes:
         - ReadWriteOnce
       resources:
         requests:
           storage: 64Mi
       storageClassName: nfs-client
       volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: common-datastore
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: nfs-client
        volumeMode: Filesystem
