apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: data-redis
  namespace: hwson
  resourceVersion: "5311712"
  uid: 9ae807cb-363c-4fe1-a89c-975da0cfcffc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-redis-storage
  volumeMode: Filesystem
  volumeName: redis-pv-volume
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  phase: Bound

