apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: events-cluster
rules:
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - watch
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: events-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: events-cluster
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: common-datastore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: common-datastore
  name: pod-exec-role
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec-rolebinding
  namespace: common-datastore
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-exec-role
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: common-datastore
